app = "audio-converter"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"
processes = []

[env]

[experimental]
  auto_rollback = true
  
[build]

  [[build.buildpacks]]
    uri = "https://github.com/heroku/heroku-buildpack-apt.git"

  [[build.buildpacks]]
    uri = "https://github.com/heroku/heroku-buildpack-python.git"

  [build.buildpacks.environment]
    APT_GET_INSTALL = "ffmpeg"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
